service: image-resize-on-the-fly-bucket-test

custom:
  secrets: ${file(../secrets/secrets.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE, 'dev'}
  profile: serverless-admin
  region: ${env:REGION}
  environment:
    BUCKET: ${env:BUCKET}

resources:
  Resources:
    ImageResizeOnTheFly:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicReadWrite
        BucketName: ${env:BUCKET}
        WebsiteConfiguration:
          ErrorDocument: error.html
          IndexDocument: index.html
          RoutingRules:
            - 
              RedirectRule:
                HostName: ${self:custom.secrets.DOMAIN}
                HttpRedirectCode: "307"
                Protocol: "https"
                ReplaceKeyPrefixWith: "${self:provider.stage}/resize?key="
              RoutingRuleCondition:
                HttpErrorCodeReturnedEquals: "404"
                KeyPrefixEquals: ""
    ImageResizeOnTheFlyPolicy:
      Type: AWS::S3::BucketPolicy
      Properties: 
        Bucket: 
          Ref: ImageResizeOnTheFly
        PolicyDocument: 
          Statement: 
            - 
              Action: 
                - "s3:*"
              Effect: "Allow"
              Resource:
                Fn::Join: 
                  - ""
                  - 
                    - "arn:aws:s3:::"
                    - 
                      Ref: ImageResizeOnTheFly
                    - "/*"
              Principal: "*"